# -*- coding: utf-8 -*-
"""YoutubeCrawling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l75biuu6jIDIwvXHjB1MMlt472n0MBke

##Download
"""

!pip install youtube_transcript_api

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import JSONFormatter
import json
import pandas as pd

def getTranscript(youtube_key):
  transcript =  YouTubeTranscriptApi.get_transcript(youtube_key)
  data = pd.DataFrame(transcript)
  return data

"""## Data
Alle Nachrichten-Videos, die im fertigen Datensatz genutzt werden. Insgesamt 68,3751 Stunden bzw. 334170 Wörter unterschiedlicher Thematiken der politik, Geschichte, Wissenschaft, Soziales, unterschiedliche Länder, Umwelt, Klimawandel, Wirtschaft, Technik, Prominente, Royals etc. 

"""

#NBC News
data = getTranscript("IxameETwHgo") #Goodbye 2021: A Year To Remember… And Forget! NBC News
data = data.append(getTranscript("Qjxs4x3_-Fw")) #Nightly News Full Broadcast - April 15 NBC News
data = data.append(getTranscript("anUrallnL3c")) #Examining The Biggest 2020 Headlines Around The World | NBC News NOW
data = data.append(getTranscript("g6H9Q8wB4h8")) #2020: The Year Of Climate Extremes | Nightly News Films NBC News
data = data.append(getTranscript("4rBXRmtbVPY")) #Nightly News Full Broadcast - Feb. 16 NBC News
data = data.append(getTranscript("w_7FMZqkQsI")) #Morning News NOW Full Broadcast - April 22 NBC News
data = data.append(getTranscript("HkFfX03iKWk")) #Suspected Tornado Leaves Seven Injured After Touching Down In Arkansas
data = data.append(getTranscript("etvC9MgBx1w")) #Southern Cities Rocked By Storms Begin Surveying The Damage
data = data.append(getTranscript("Vh5_h1buT2A")) #Texas Town Hit By Major Tornado As Severe Weather Sweeps Across The U.S.
data = data.append(getTranscript("xXpeEXE3jEU")) #Space X Dragon Capsule Makes Historic Splashdown
data = data.append(getTranscript("nK5CkeEKi2s")) #Space Capsule To Splashdown In Ocean

data = data.append(getTranscript("Q28CCU3XMlU")) #SpaceX’s All-Civilian Inspiration4 Crew Orbiting Earth
data = data.append(getTranscript("L6qabHnHoJ0")) #SpaceX Launches New Era Of Space Tourism
data = data.append(getTranscript("I6hv_oCRa4Q")) #Companies Manufacture In Space As Part Of Growing Industry
data = data.append(getTranscript("iW7qpMlksn0")) #WATCH: SpaceX Launch First All-civilian Inspiration4 Crew Into Orbit
data = data.append(getTranscript("OJxpwujBTvg")) #FAA Grounds Virgin Galatic's Spacecraft Amid Investigation Into Warning Light
data = data.append(getTranscript("5OUKHRUuf3E")) #Hubble Space Telescope Captures 'Einstein Ring'
data = data.append(getTranscript("1PRUx52t5y8")) #Watch: Northrop Grumman Launches Cygnus Spacecraft To ISS
data = data.append(getTranscript("xCfSJj1iyIU")) #China Launches First Crewed Space Mission Since 2016
data = data.append(getTranscript("ZmuLSPosiEA")) #Watch: SpaceX Launches Resupply Mission to International Space Station
data = data.append(getTranscript("4rNCHHgoIKo")) #Remembering Jay Barbree, NBC News Space Correspondent | Meet The Press
data = data.append(getTranscript("rV1p1DsucG8")) #SpaceX Mission Landing Marks A New Era For NASA | NBC Nightly News
data = data.append(getTranscript("LFUyoPYKhPY")) #Meet The Crew of Inspiration4, The First All-Civilian Space Mission | NBC Nightly News
data = data.append(getTranscript("nhtZfs6QQpc")) #Astronauts Aboard International Space Station Welcome SpaceX 2 Crew | NBC News
data = data.append(getTranscript("mF-rkEFahbU")) #SpaceX Launches Astronauts To Space Station On Reused Rocket | NBC Nightly News
data = data.append(getTranscript("Hbh6-sska08")) #SpaceX Sends 4 Astronauts Into Space In Reused Rocket | NBC News NOW
data = data.append(getTranscript("HqGp10ocHrc")) #SpaceX Falcon 9 Rocket With Crew Dragon Capsule Lifts Off From Kennedy Space Center | NBC News NOW
data = data.append(getTranscript("spbvXHks38U")) #The Complicated History Of America, Russia, And Outer Space | NBC News NOW
data = data.append(getTranscript("vzasOk6kfkg")) #Watch: Soyuz Spacecraft Carries Nasa Astronaut To International Space Station | NBC News NOW

data = data.append(getTranscript("FuMr3b_rpn8")) #'I'm Going To See The Vastness Of Space': William Shatner On Heading To Space
data = data.append(getTranscript("klxxmgWI2EI")) #Space: Billionaires Vs. Nation States | Meet The Press Reports
data = data.append(getTranscript("Pw8HNep1RX4")) #Blue Origin Launch Sending William Shatner To Space Delayed
data = data.append(getTranscript("YgdoeXnbDXc")) #Watch: William Shatner Goes Into Space On Blue Origin Flight
data = data.append(getTranscript("F5N2j4REwxg")) #WATCH: Actor William Shatner Becomes Oldest Person To Travel To Space Aboard Blue Origin Rocket
data = data.append(getTranscript("LBDzG0i6MMo")) #Perseverance Rover Finds Evidence Of Ancient River on Mars
data = data.append(getTranscript("Z7LcYMMcItc")) #China’s Historic Mission To New Space Station
data = data.append(getTranscript("3dr7GeHiS4E")) #James Webb Telescope Launches Into Space
data = data.append(getTranscript("0nH5vEoFRcs")) #Exclusive Look At Rover That Could Be Heading To The Moon
data = data.append(getTranscript("MF25uhXVE5M")) #Watch: SpaceX, Axiom Launch First Private Mission to ISS

data = data.append(getTranscript("5xL6eaiM14o")) #Full Speech: Pres. Bush Speaks At Shanksville 9/11 Ceremony
data = data.append(getTranscript("wAa6v9Kvf58")) #20 Years Later, 9/11 Witnesses Still Feel The Pain
data = data.append(getTranscript("Q9nyx9AxkLM")) #‘When The Towers Began To Collapse, The Entire Country Shuddered’
data = data.append(getTranscript("0oHOcuMlgHA")) #Lester Holt Reflects On Where America Is Now, 20 Years After 9/11
data = data.append(getTranscript("CeMlIcWSJac")) #New Flight Carrying Americans Out of Afghanistan
data = data.append(getTranscript("GjZRs1S27bM")) #Full Special: ‘America Remembers 9/11: 20 Years Later’ | NBC News NOW
data = data.append(getTranscript("eI6go8kFEOk")) #FBI Releases Declassified Document Into Links Between Saudi Arabia And 9/11
data = data.append(getTranscript("AnmT1UYXMw8")) #Answering Kids’ Questions About 9/11 | Nightly News: Kids Edition
data = data.append(getTranscript("7ozp3Rhg_gU")) #‘Unity Is Possible in America’: Harris Honors 9/11 Anniversary
data = data.append(getTranscript("AWQKY5OC3W4")) #Sons Reflect On Mother’s ‘Hero’s Legacy’ 20 Years After Flight 93
data = data.append(getTranscript("MGS06T3aB9A")) #20 Years After 9/11, Condoleezza Rice Discusses Security Risks

data = data.append(getTranscript("DN8y6ULYBLY")) #America Remembers: FDNY Chief Looks Back On 9/11 Attacks | Nightly News Films
data = data.append(getTranscript("ow22zUAPD2Y")) #Meet The FDNY Firefighters Who Served in Air Force Together After 9/11
data = data.append(getTranscript("AexdEjBqNA4")) #20 Years Later: Revisiting Elementary School Near World Trade Center

#NOW Tonight with Joshua Johnson NBC News
data = data.append(getTranscript("bbllul8WWxU")) #New Technology May Store Captured Carbon Dioxide In Concrete
data = data.append(getTranscript("SUL6AECe2P4")) #NOW Tonight with Joshua Johnson - April 22 | NBC News NOW
data = data.append(getTranscript("uzmlTnvu5qE")) #Florida Rep. Randy Fine Sponsors Bill To Dissolve Disney's Special Governing Status
data = data.append(getTranscript("sOEN8sx50mY")) #NOW Tonight with Joshua Johnson - April 21 | NBC News NOW
data = data.append(getTranscript("66ZSTLDxCA8")) #NOW Tonight with Joshua Johnson - April 20 | NBC News NOW
data = data.append(getTranscript("evsAFTrJci0")) #New Jersey Community Prioritizes Social Equity In Recreational Marijuana Rollout
data = data.append(getTranscript("DndEXYA0Bdw")) #Train Operators Help Evacuate Millions Of Ukrainians To Safety
data = data.append(getTranscript("CHu84LD0Qco")) #NOW Tonight with Joshua Johnson - April 19 | NBC News NOW
data = data.append(getTranscript("3qhVkcnNlH4")) #Violent Crime Rates Surge In U.S. During The Pandemic
data = data.append(getTranscript("ZPp75CTnXcc")) #NOW Tonight with Joshua Johnson - April 18 | NBC News NOW
data = data.append(getTranscript("kFUrQZ9Z5z0")) #Photographing The War In Ukraine
data = data.append(getTranscript("CmJKJ5SqT1c")) #NOW Tonight with Joshua Johnson - April 15 | NBC News NOW
data = data.append(getTranscript("Yt8ur-Huv9U")) #NOW Tonight with Joshua Johnson - April 13 | NBC News NOW
data = data.append(getTranscript("pCfeuXh_HIU")) #Nonprofit Group Helps Support Orphanages Across Ukraine
data = data.append(getTranscript("bEQOuc2YOro")) #NOW Tonight with Joshua Johnson - April 12 | NBC News NOW
data = data.append(getTranscript("L_If2-RoEXM")) #NOW Tonight with Joshua Johnson - April 11 | NBC News NOW
data = data.append(getTranscript("h6-VjiRItoM")) #Campaign For 4-Day Work Week Gains Momentum
data = data.append(getTranscript("znGBpYQgbtE")) #NOW Tonight with Joshua Johnson - April 8 | NBC News NOW
data = data.append(getTranscript("qKqoZ5n3y0Q")) #NOW Tonight with Joshua Johnson - April 7 | NBC News NOW
data = data.append(getTranscript("u4dMVzNltU4")) #NOW Tonight with Joshua Johnson - April 6 | NBC News NOW
data = data.append(getTranscript("xffN-T_X29s")) #American Instagram Influencer Documents Her Escape From Ukraine Online
data = data.append(getTranscript("j2goPEaCBgc")) #NOW Tonight with Joshua Johnson - Apr. 5 | NBC News NOW
data = data.append(getTranscript("dYHPF4IDbCA")) #NOW Tonight With Joshua Johnson - April 4 | NBC News NOW
data = data.append(getTranscript("KIibeza0VeU")) #NOW Tonight with Joshua Johnson - Apr. 1 | NBC News NOW
data = data.append(getTranscript("kXGTaEZVBEA")) #Advocates Push For Easier Access To Opioid Agonists Treatments
data = data.append(getTranscript("qcWLjX2mn_w")) #NOW Tonight with Joshua Johnson - March 31 | NBC News NOW
data = data.append(getTranscript("luDaWQTaz7w")) #ALS Drug Fails To Win Recommendation From FDA Advisory Panel
data = data.append(getTranscript("OL_YTIxdbns")) #NOW Tonight with Joshua Johnson - March 30 | NBC News NOW
data = data.append(getTranscript("EyMNIR1eCh8")) #NOW Tonight with Joshua Johnson - March 29 | NBC News NOW
data = data.append(getTranscript("tQrk97WXwIs")) #NOW Tonight With Joshua Johnson - March 28 | NBC News NOW
data = data.append(getTranscript("wo1plyzmVdE")) #Congress Recommends Holding Trump Aides Scavino, Navarro In Contempt
data = data.append(getTranscript("OFlnayFg1e8")) #NOW Tonight With Joshua Johnson - March 25 | NBC News NOW
data = data.append(getTranscript("DYEvyYdK9T8")) #How UNICEF's Humanitarian Effort Is Helping Ukraine
data = data.append(getTranscript("5FtANGcfobU")) #NOW Tonight with Joshua Johnson - March 24 | NBC News NOW
data = data.append(getTranscript("-tRF0GxS29U")) #How The Pandemic Highlights The Connection Between Health And Environment
data = data.append(getTranscript("zcqj59uYIl4")) #NOW Tonight with Joshua Johnson - March 23 | NBC News NOW
data = data.append(getTranscript("t3vRLAoAwSM")) #NOW Tonight With Joshua Johnson - March 22 | NBC News NOW
data = data.append(getTranscript("f00fwYZ8m5w")) #NOW Tonight with Joshua Johnson - March 21 | NBC News NOW
data = data.append(getTranscript("b9Wk7FE0bbA")) #Experts Answer Viewer Questions On The War In Ukraine
data = data.append(getTranscript("9PokW0QOZGA")) #What It's Like Reporting On The War In Ukraine
data = data.append(getTranscript("jwT-70TmSJQ")) #NOW Tonight with Joshua Johnson - March 3 
data = data.append(getTranscript("qKqoZ5n3y0Q")) #NOW Tonight with Joshua Johnson - April 7 | NBC News NOW
data = data.append(getTranscript("u4dMVzNltU4")) #NOW Tonight with Joshua Johnson - April 6 | NBC News NOW
data = data.append(getTranscript("xffN-T_X29s")) #American Instagram Influencer Documents Her Escape From Ukraine Online
data = data.append(getTranscript("j2goPEaCBgc")) #NOW Tonight with Joshua Johnson - Apr. 5 | NBC News NOW
data = data.append(getTranscript("dYHPF4IDbCA")) #NOW Tonight With Joshua Johnson - April 4 | NBC News NOW
data = data.append(getTranscript("KIibeza0VeU")) #NOW Tonight with Joshua Johnson - Apr. 1 | NBC News NOW
data = data.append(getTranscript("kXGTaEZVBEA")) #Advocates Push For Easier Access To Opioid Agonists Treatments
data = data.append(getTranscript("qcWLjX2mn_w")) #NOW Tonight with Joshua Johnson - March 31 | NBC News NOW
data = data.append(getTranscript("luDaWQTaz7w")) #ALS Drug Fails To Win Recommendation From FDA Advisory Panel
data = data.append(getTranscript("OL_YTIxdbns")) #NOW Tonight with Joshua Johnson - March 30 | NBC News NOW
data = data.append(getTranscript("EyMNIR1eCh8")) #NOW Tonight with Joshua Johnson - March 29 | NBC News NOW
data = data.append(getTranscript("tQrk97WXwIs")) #NOW Tonight With Joshua Johnson - March 28 | NBC News NOW
data = data.append(getTranscript("wo1plyzmVdE")) #Congress Recommends Holding Trump Aides Scavino, Navarro In Contempt
data = data.append(getTranscript("OFlnayFg1e8")) #NOW Tonight With Joshua Johnson - March 25 | NBC News NOW
data = data.append(getTranscript("DYEvyYdK9T8")) #How UNICEF's Humanitarian Effort Is Helping Ukraine
data = data.append(getTranscript("5FtANGcfobU")) #NOW Tonight with Joshua Johnson - March 24 | NBC News NOW
data = data.append(getTranscript("-tRF0GxS29U")) #How The Pandemic Highlights The Connection Between Health And Environment
data = data.append(getTranscript("zcqj59uYIl4")) #NOW Tonight with Joshua Johnson - March 23 | NBC News NOW
data = data.append(getTranscript("t3vRLAoAwSM")) #NOW Tonight With Joshua Johnson - March 22 | NBC News NOW
data = data.append(getTranscript("f00fwYZ8m5w")) #NOW Tonight with Joshua Johnson - March 21 | NBC News NOW
data = data.append(getTranscript("b9Wk7FE0bbA")) #Experts Answer Viewer Questions On The War In Ukraine
data = data.append(getTranscript("9PokW0QOZGA")) #What It's Like Reporting On The War In Ukraine
data = data.append(getTranscript("jwT-70TmSJQ")) #NOW Tonight with Joshua Johnson - March 3

#BBC News
data = data.append(getTranscript("QtBS8COhhhM")) #Prince Andrew & the Epstein Scandal: The Newsnight Interview - BBC News
data = data.append(getTranscript("vraVCUerVOk")) #Deaths reported at Kabul airport as Afghans try to flee Taliban - BBC News
data = data.append(getTranscript("I8PhhS9OhUo")) #NATO leaders meet in Brussels - BBC News
data = data.append(getTranscript("FpQhITrunPI")) #China's population grows at slowest pace in decades - BBC News
data = data.append(getTranscript("HPMBehhdMkc")) #Libya: A decade on the frontline - BBC News
data = data.append(getTranscript("6fT6ByzQsKY")) #The Duke of Edinburgh, Prince Philip has died aged 99 - BBC News
data = data.append(getTranscript("6zppLq0KcpQ")) #Putin tells forces to seal off last Mariupol fighters - BBC News
data = data.append(getTranscript("vBjabNusoKM")) #UN scientists say it's 'now or never' to limit global warming - BBC News
data = data.append(getTranscript("prfkmgeoCsc")) #Ukraine war ‘a horror story of violations against civilians’ - BBC News

#Sky News
data = data.append(getTranscript("HLrg-fpVo_c")) #2020: A Year To Forget? Sky News
data = data.append(getTranscript("rS53tpD0L6A")) #Through The Storm: Inside The COVID Wards Sky News
data = data.append(getTranscript("UFHRZ0zyYQU")) #Two medals for Team GB in the Tokyo Olympics
data = data.append(getTranscript("JH3a-hBEUhk")) #Tokyo Olympics: Mixed emotions as Bradly Sinden takes silver
data = data.append(getTranscript("11r_nfmmdsk")) #Sinden wins Silver at Tokyo 2020 in the taekwondo final
data = data.append(getTranscript("d7kTSVBcK9Q")) #Team GB wins first medal of Tokyo Olympic Games
data = data.append(getTranscript("Pm85v2H-QFs&list")) #Tokyo Olympics: Jade Jones suffers shock defeat in taekwondo as Andy Murray pulls out
data = data.append(getTranscript("xuqJ8HMYeWM")) #Tokyo Olympics: Team GB gaining momentum
data = data.append(getTranscript("ztEo3H4ukvQ")) #Tokyo Olympics: Are the games the place to protest?
data = data.append(getTranscript("N0dd5UisPwE")) #Tokyo Olympics opens to a virtual audience

data = data.append(getTranscript("bLFYChw5c0Y")) #Clean energy's dirty secret: the pond in China filled with toxic leftovers
data = data.append(getTranscript("66mHa1hasec")) #Solar power generation being ignored in the UK?
data = data.append(getTranscript("ZrCXJCW5d9Y")) #Coal supply crisis for heritage steam trains
data = data.append(getTranscript("ipsC0Pqvd6w")) #Farmers say solar farms on fertile land is a 'waste'
data = data.append(getTranscript("eY16RJXiTo0")) #'Just Stop Oil' activists glue their hands to roads and tankers in protest
data = data.append(getTranscript("I4GFcvFf3I4")) #Climate activist interviewed while glued to road
data = data.append(getTranscript("KZiwvKw1j2M")) #Will more wind farms solve the UK's energy crisis?
data = data.append(getTranscript("3Jx1bNhxltQ")) #Climate: Is the UK's new energy strategy realistic?
data = data.append(getTranscript("FQ6yO7cac6M")) #Climate Change: UN warns global warming is set to be more than double agreed 1.5 degree limit

data = data.append(getTranscript("E_ECEgZ4RWk")) #Can Boris Johnson survive his leadership crisis?
data = data.append(getTranscript("eGYe788qU3Y")) #Energy price cap to rise to £1,971
data = data.append(getTranscript("gpkLageRBMY")) #Cost of Living: PM's 'mega package' to help people with the price spike
data = data.append(getTranscript("AoH5p6ehLH8")) #Inflation could peak at 7.25% by next April
data = data.append(getTranscript("S3VMDC3LpBQ")) #Cost of living: Energy prices to 'stay high for two years'
data = data.append(getTranscript("kUuGKkJ3fPs")) #Energy prices: How will the government help?
data = data.append(getTranscript("B3EJYzbdUg8")) #Labour MP on energy price hike: 'Shocking levels of increases'
data = data.append(getTranscript("FR3o-gxccyc")) #Sky News Breakfast: Fuel bills could keep on rising for years
data = data.append(getTranscript("uaibuZHMdFk")) #Cost of Living: The battle to keep homes warm
data = data.append(getTranscript("YOzoWh2KI44")) #Bank of England Governor: 'Interest rates need to rise'
data = data.append(getTranscript("aUv3iciEMUM")) #Analysis: Why the energy price cap needs to rise
data = data.append(getTranscript("l5mVYOZNASc")) #The Daily Climate Show: Is poor power adding to the cost of living crisis?
data = data.append(getTranscript("y6oyTqeMw1o")) #Cost of living crisis: Eat or heat a 'huge reality', as councils face 'unprecedented' pleas for help
data = data.append(getTranscript("X3pUA6O-Qzk")) #Dogs purchased in lockdown are being abandoned
data = data.append(getTranscript("D8CggzWnYMI")) #Cost of living crisis: Protesters chant 'tax the rich' across the UK
data = data.append(getTranscript("qmsI1BwpDhU")) #Fears of war in Ukraine push up prices at the pump
data = data.append(getTranscript("Yn8KzexBMFc")) #Cost of living crisis: Thousands of renters could lose homes within months
data = data.append(getTranscript("KV4slXmfheI")) #Ukraine Crisis: What price is the UK willing to pay?
data = data.append(getTranscript("cIY2X7KYW9E")) #Inflation bites: why living standards are set for largest drop since 1950s
data = data.append(getTranscript("7VAlC9yQjqE")) #Spring Statement: Chancellor says he 'can't protect everyone from global challenges we face'
data = data.append(getTranscript("ZXUKtI061D8")) #Spring Statement: Tax, fuel duty and NI cuts in Rishi Sunak's mini-budget
data = data.append(getTranscript("k88XuVrCTqU")) #Spring Statement: Surging inflation hitting British businesses
data = data.append(getTranscript("NLeBaCb_WvM")) #Spring Statement: Residents in Bury suffering as cost of living crisis bites
data = data.append(getTranscript("1s-er7BPdQg")) #Spring Statement: UK's poorest 'are my priority' - Chancellor
data = data.append(getTranscript("_nXKUemXXBQ")) #Sky News Breakfast: Could the UK be doing more to stop Putin?
data = data.append(getTranscript("qAXCH7VsDTs")) #Spring Statement: Poorer households have 'nothing left to give' warns Labour
data = data.append(getTranscript("3MRGe15ydE0")) #Former Chancellor says the economy faces 'an acute crisis'
data = data.append(getTranscript("fmRRKzCg6Bw")) #UK energy bill spending set to reach highest levels since the 1950s
data = data.append(getTranscript("qKLuHHnSRfo")) #What is the future for nuclear power in Britain?
data = data.append(getTranscript("hWOYKVhSXBM")) #Cost of Living Crisis: Former PM Gordon Brown urges action on child poverty
data = data.append(getTranscript("siaOD2pnfoU")) #PMQs: 'What a load of baloney' Ian Blackford reacts to PM after cost of living question
data = data.append(getTranscript("imA6kTD8Lbs")) #Watch live: Senior MPs question Prime Minister Boris Johnson

#The Economist
data = data.append(getTranscript("iTLssSIetq0")) #The World in 2021: five stories to watch out for | The Economist
data = data.append(getTranscript("uynhvHZUOOo")) #See what three degrees of global warming looks like | The Economist
data = data.append(getTranscript("K7lzhYTg94s")) #Why politicians have failed to tackle climate change | The Economist
data = data.append(getTranscript("fSGorwtY-zM")) #How scientists calculate climate change | The Economist
data = data.append(getTranscript("yhlg9txl7yM")) #The carbon cycle is key to understanding climate change | The Economist
data = data.append(getTranscript("aM31RyxSSCw")) #What is net zero? | The Economist
data = data.append(getTranscript("fkX-H24Chfw")) #Hydrogen: fuel of the future? | The Economist
data = data.append(getTranscript("m5ych9oDtk0")) #How do carbon markets work? | The Economist
data = data.append(getTranscript("T1FdIvLg6i4")) #Why it's harder to earn more than your parents | The Economist
data = data.append(getTranscript("J97rj__zCxE")) #Can science help poor kids earn more? | The Economist

data = data.append(getTranscript("IzvgEs1wPFQ")) #How to make computers less biased | The Economist
data = data.append(getTranscript("F7DpdOHRDR4")) #Gene editing: should you be worried? | The Economist
data = data.append(getTranscript("dFMMssyRsWo")) #Climate change technology: is shading the earth too risky? | The Economist
data = data.append(getTranscript("oUvvfHkXyOA")) #How data transformed the NBA | The Economist
data = data.append(getTranscript("BSnPqvsFpJM")) #Cycling's speed secrets | The Economist
data = data.append(getTranscript("oZt6io7JmW8")) #How economic policy can help the world recover | The Economist
data = data.append(getTranscript("O8-uCob-_XE")) #Will you be eating insects soon? | The Economist
data = data.append(getTranscript("0xSSonMIqBk")) #How AI can make health care better | The Economist
data = data.append(getTranscript("3PYYadvwkOo")) #Cash from trash: could it clean up the world? | The Economist
data = data.append(getTranscript("U7qdDJt-I64")) #What’s the future of food? | The Economist
data = data.append(getTranscript("98Xvl-uTmlw")) #How vegan burgers can help save the planet | The Economist
data = data.append(getTranscript("Ms--0d7Oh0s")) #Green energy: Which sources are the most sustainable? | The Economist
data = data.append(getTranscript("0iQTRTaVqrI")) #Keeping warm, without warming the planet | The Economist
data = data.append(getTranscript("_NyKG_dVeBE")) #Green building: can mushrooms help? | The Economist
data = data.append(getTranscript("QnN4pZtf7aE")) #Sustainable materials: is there a concrete solution? | The Economist
data = data.append(getTranscript("Df7WO6rbLqc")) #Covid-19: How dangerous is Omicron? | The Economist

data = data.append(getTranscript("pFaGbtDJFwA")) #Covid-19: why your life will never be the same again | The Economist
data = data.append(getTranscript("1enhWlayMdo")) #Did covid-19 leak from a Chinese lab? | The Economist
data = data.append(getTranscript("kXlhv9eY918")) #Covid-19: how many people have died? | The Economist
data = data.append(getTranscript("RyWdIm57fpE")) #Can vaccine passports kickstart the economy? | The Economist
data = data.append(getTranscript("ad-GuV6YIMI")) #The future of shopping: what's in store? | The Economist
data = data.append(getTranscript("NHFWuRYcUp4")) #How to crunch covid-19 data | The Economist
data = data.append(getTranscript("4J97hPjls2Y")) #How will covid-19 change travel? | The Economist
data = data.append(getTranscript("8EYnsgaJo8A")) #Christine Lagarde: How covid-19 will shape Europe | The Economist
data = data.append(getTranscript("5CNc-9Zm90A")) #Covid-19 vaccines: what information can you trust? | The Economist
data = data.append(getTranscript("X5ZmfC2_j9I")) #Covid-19: what will it take to vaccinate the world? | The Economist
data = data.append(getTranscript("8Enam9uNqb4")) #Inflation: could covid-19 cause prices to rise? | The Economist
data = data.append(getTranscript("60AjDw492RU")) #Care after covid: the future of elderly health-care | The Economist
data = data.append(getTranscript("3EK4VRmG3yM")) #Covid-19: why vaccine mistrust is growing | The Economist
data = data.append(getTranscript("p0tCPwyJ6JI")) #Covid-19: how to fix the economy | The Economist
data = data.append(getTranscript("zZnjIWXUHjM")) #America’s stimulus package: is it working? | The Economist

data = data.append(getTranscript("FgR6t7vQtn8")) #Covid-19: When will a vaccine be ready? | The Economist
data = data.append(getTranscript("PAs0gw1zIuQ")) #Covid-19: why travel will never be the same | The Economist
data = data.append(getTranscript("pnKsrKuUfBc")) #Covid-19: what will happen to the global economy? | The Economist
data = data.append(getTranscript("MxDVucUZCnc")) #Covid-19: is working from home really the new normal? | The Economist
data = data.append(getTranscript("uOY32cU0ePc")) #Covid-19: what you need to know about the second wave | The Economist
data = data.append(getTranscript("7tziw5i3vy8")) #Covid-19: what’s really going on in Russia? | The Economist
data = data.append(getTranscript("f9v6givfTEA")) #Covid-19: why the economy could fare worse than you think | The Economist
data = data.append(getTranscript("VfKfSUqn_GY")) #How covid-19 could change the financial world order | The Economist
data = data.append(getTranscript("HuFFAAIbzPQ")) #Covid-19: what the world has learned during lockdown | The Economist
data = data.append(getTranscript("4Lm4pwFl_Ag")) #Covid-19: the right way to leave lockdown | The Economist
data = data.append(getTranscript("HMLop-jR8cw")) #Covid-19: Why is America's death toll so high? | The Economist
data = data.append(getTranscript("wUUWoN4LKuE")) #Covid-19: how bad will it be for the economy? | The Economist
data = data.append(getTranscript("4oQ4ayKrIHk")) #Covid-19: more questions about coronavirus, answered | The Economist
data = data.append(getTranscript("Lf1TNwWDQNk")) #Covid-19: your questions about coronavirus, answered | The Economist
data = data.append(getTranscript("2rLoPBPa2Z0")) #The new coronavirus: how should the world respond? | The Economist

data = data.append(getTranscript("BFtrZ0aqqtM")) #Can conservation save our ocean? | The Economist
data = data.append(getTranscript("_hgk_gWOVK8")) #Exploring and protecting the Antarctic | The Economist
data = data.append(getTranscript("BudHTnb9G5s")) #Can eco-tourism help save the ocean? | The Economist
data = data.append(getTranscript("dA6uLyZ5dx4")) #Can technology save the rarest creatures on the planet? | The Economist
data = data.append(getTranscript("K6R-WGOqjC0")) #Discover Hyderabad | The Economist
data = data.append(getTranscript("sCi4FBN-7dA")) #Discover Miami: travel the bars and beaches with the locals | The Economist
data = data.append(getTranscript("4COeTrjB6hA")) #Discover Colombo: travel in the fastest-growing city in the world | The Economist
data = data.append(getTranscript("q0pMg6rvc0s")) #Discover Buenos Aires: slabs of meat, Malbec and polo | The Economist
data = data.append(getTranscript("mIEsgVd17v8")) #Discover London: royal shopping and wild-swimming | The Economist
data = data.append(getTranscript("cNIrkT3WB24")) #Discover Osaka: sushi, tattoos, and a flourishing nightlife | The Economist
data = data.append(getTranscript("AJ38SiVOD78")) #Oil and gas companies are facing major technological disruption
data = data.append(getTranscript("aqz3DaisBz8")) #The music industry and the digital revolution
data = data.append(getTranscript("e2rBzJXLem8")) #The future of the car industry | The Economist

# Stars News
data = data.append(getTranscript("Q2TZJ3WvDoA")) #Is Shia Labouf New Tattoo is Real?
data = data.append(getTranscript("1qHdk7dVqeM")) #Sylvester Stallone's Sassy Daughter | Scarlet Rose Stallone | What Is She Doing Now ?
data = data.append(getTranscript("soyWr0yeEw4")) #Spiritual Life of Tom Hanks
data = data.append(getTranscript("zjIjQpBSG5c")) #Dolph Lundgren's Daughters | Ida & Greta | What Are They Doing Now ?
data = data.append(getTranscript("uvQmcMBHbw8")) #Johnny Depp's Daughter Is A Born Star | Lily-Rose Depp
data = data.append(getTranscript("NsvdzhKywJU")) #Sylvester Stallone's First Daughter | Sophia Stallone | What Is She Doing Now ?

data = data.append(getTranscript("J_Rq0j9VoiQ")) #Alexandra Daddario's Boyfriend | Brendan Wallace
data = data.append(getTranscript("so8BVyT-8S8")) #Mr Bean's Son | Benjamin Atkinson | What Is He Doing Now ?
data = data.append(getTranscript("SsREE_573eg")) #What Does Paul Walker's Daughter Do? | Meadow Rain Walker
data = data.append(getTranscript("I6h8ZIxxE_Y")) #Paul Walker's Brothers | What Are They Doing Now ?

data = data.append(getTranscript("kXf5R4Lcdyw")) #Jason Momoa's Wife | Lisa Bonet | What Is She Doing Now ?
data = data.append(getTranscript("N9g-OSg-Lm8")) #Donnie Yen's Wife | Cissy Wang | What Is She Doing Now ?
data = data.append(getTranscript("NElw8sRgDUg")) #Oprah Winfrey's Partner | Stedman Graham | What Is He Doing Now ?
data = data.append(getTranscript("R6cJ57G1psE")) #Three People Paris Jackson Loves In Her Life
data = data.append(getTranscript("MVyarRw2VOU")) #Who Is The Margot Robbie's Husband ?
data = data.append(getTranscript("DIYdH9fjUP4")) #Leonardo Dicaprio's Girlfriend | Camila Morrone

data = data.append(getTranscript("OIMJHF98Npo")) #Miley Cyrus' Handsome Boyfriend | Cody Simpson
data = data.append(getTranscript("Atka2vCdU7A")) #Who Is The Alexander Ludwig's Girlfriend ? | Vikings ( Bjorn Ironside )
data = data.append(getTranscript("AX7IUTwUQ1g")) #Timothee Chalamet Relationship Timeline
data = data.append(getTranscript("S9SkZvPJbX4")) #Jason Statham's Partner | Rosie Huntington Whiteley | What Is She Doing Now ?

data = data.append(getTranscript("CX4g-GCJe5s")) #Avatar 2 | What We Know So Far?
data = data.append(getTranscript("NnQXT8vJcWo")) #Lily Collins Boyfriend | Charlie McDowell
data = data.append(getTranscript("DpNRFVWLiV0")) #Zac Efron's Girlfriend | Vanessa Valladares
data = data.append(getTranscript("2IApoKu-vWk")) #Phoebe Tonkin's Boyfriend | Alex Greenwald
data = data.append(getTranscript("nsF1Sz1jAKc")) #The Man Behind Spiderman Tom Holland Bio

data = data.append(getTranscript("W3qZIPiWKc4")) #The News You Missed in 2021, From Every Country in the World (Part 1) Wendover Production
data = data.append(getTranscript("Y413Czri6qw")) #The News You Missed in 2021, From Every Country in the World (Part 2) Wendover Production
data = data.append(getTranscript("6dzKQLTMxkk")) #Top 10 Celebrity News Stories That Broke The Internet WatchMojo.com
data = data.append(getTranscript("FMM7GWnAv0A")) #2021's Biggest Breakthroughs in Physics Quanta Magazine
data = data.append(getTranscript("6Pm0Mn0-jYU")) #Why Finland And Denmark Are Happier Than The U.S. CNBC Make it
data = data.append(getTranscript("UNgVS0IiG-I")) #Watch Rachel Maddow Highlights: April 22 MSNBC
data = data.append(getTranscript("1KtTAb9Tl6E")) #Why Global Supply Chains May Never Be the Same | A WSJ Documentary
data = data.append(getTranscript("YRvf00NooN8")) #Elon Musk: A future worth getting excited about | TED | Tesla Texas Gigafactory interview
data = data.append(getTranscript("JC-qGzTIpEo")) #How the Fashion Industry Needs to Change | Good Morning Vogue
data = data.append(getTranscript("XljR6oxL4i0")) #Lindsay Lohan Breaks Down 18 Looks From 1998 to Now | Life in Looks | Vogue

#BBC World Service
data = data.append(getTranscript("7SBJ1V5iS_g")) #The women trying to stop a nuclear war - BBC World Service

data = data.append(getTranscript("0MFdNTryTdg")) #Shirley Chisholm: The first black woman to run for US president - BBC World Service
data = data.append(getTranscript("D6ObHc14874")) #'I nearly died rowing the Atlantic' - BBC World Service

data = data.append(getTranscript("mY8e5k45z6k")) #From the Carribbean to Britain - a journey on the Empire Windrush - BBC World Service podcast
data = data.append(getTranscript("oi4Ll7VGXJk")) #WW2 'Brown Babies': A little-known part of British 20th Century history - BBC World Service podcast
data = data.append(getTranscript("1Gig1bhwI4c")) #London's first black policeman: 'A job that had to be done' - BBC World Service podcast
data = data.append(getTranscript("o3wWbQVAyJc")) #'I started a publishing revolution' - BBC World Service

data = data.append(getTranscript("WBeZigeTL4g")) #'I was Britain's first black headteacher' - BBC World Service
data = data.append(getTranscript("-H943N5IuT4")) #LGBT protest: 'I stormed BBC News live on air' - BBC World Service
data = data.append(getTranscript("MT5p6h9kh18")) #The father of snow boarding - BBC World Service

data = data.append(getTranscript("0bNAe9MxGro")) #'We’ve escaped Ukraine, but my father is still there' - BBC World Service
data = data.append(getTranscript("XIUDQSFpK6g")) #Helping your child with anxiety - BBC World Service, Health Check

data = data.append(getTranscript("1n7zuAHyXX0")) #Cricket’s keeping me in Kyiv – Stumped, BBC World Service
data = data.append(getTranscript("mZxyaFhDo6Y")) #The truth about rape in India - @BBC World Service

#MSNBC
data = data.append(getTranscript("Jsys1HR_fbw")) #Biden Stressed Importance Of Democracies Over Autocracies: White House
data = data.append(getTranscript("4t8xa2w2FYY")) #Joe: A Return To Normalcy For The State of the Union Address
data = data.append(getTranscript("DZCjUnNVgqo")) #Watch Highlights From Biden's First State Of The Union Address
data = data.append(getTranscript("8PTBzbrRyBA")) #'Spare A Thought For Gov. Reynolds': Unpacking The State Of The Union Rebuttal
data = data.append(getTranscript("58pZG78Ay-8")) #The Hits Biden Didn't Take During His State Of The Union Address
data = data.append(getTranscript("SFpNdm4iPAo")) #Amid War And Plague, Biden Tells The Country 'It's Going To Be OK'
data = data.append(getTranscript("qQhbjRDMy74")) #Putin ‘Badly Miscalculated’ By Invading Ukraine Says Biden
data = data.append(getTranscript("LwYqJxIDgVs")) #Meet The Republican Delivering The Biden Rebuttal | The Mehdi Hasan Show

data = data.append(getTranscript("qi5uSRJdosc")) #Inside Biden’s Crucial Speech Amid Global Clash with Putin
data = data.append(getTranscript("0h7Mtm02edE")) #As Biden Stares Down Putin, Go Inside White House For High Stakes Address I MSNBC Exclusive
data = data.append(getTranscript("7mWDYrSatLA")) #Michael Beschloss: Biden Needs To Talk About Democracy In ‘Existential Danger’
data = data.append(getTranscript("9qGA1JxRz_o")) #Joe: The President Tonight Needs To Channel Churchill, JFK, Reagan
data = data.append(getTranscript("QlpSbLLL7ao")) #White House Infrastructure Coordinator Talks State of the Union Address
data = data.append(getTranscript("bcWmcGK2VnE")) #Watch Morning Joe Highlights: April 22 | MSNBC
data = data.append(getTranscript("rX1qL2BxFZw")) #The Right Wants Freedom For Themselves And Not For Others: David French
data = data.append(getTranscript("Ex7QA4jHsjc")) #Biden Having To Walk And Chew Gum At Same Time On Energy: EPA Administrator

data = data.append(getTranscript("V7YYLfq9Aqc")) #Pentagon: There Will Be No U.S. Forces Fighting In Ukraine In This War
data = data.append(getTranscript("zIGJYFqdz3c")) #Florida House Passes Bill Stripping Disney Of Self-Governing Status
data = data.append(getTranscript("UgNjUF7QV9E")) #Audio Confirms Kevin McCarthy Wanted Trump Out After January 6
data = data.append(getTranscript("TF8cWRr8--Q")) #Watch Morning Joe Highlights: April 21 | MSNBC
data = data.append(getTranscript("VXB6ujdO0F0")) #Macron And Le Pen Go Head-To-Head In Presidential Debate
data = data.append(getTranscript("S_ZUDMmcyFY")) #What Russia's Losses In Ukraine Could Mean For Putin And Russia
data = data.append(getTranscript("Llgg8dSkBiA")) #Netflix Stock Tumbles 35 Percent After Losing Subscribers
data = data.append(getTranscript("IoJAchKoriQ")) #Why Putin Declaring Success In Mariupol Is 'Face-Saving Theater'

data = data.append(getTranscript("9PDcowdq7gw")) #Ukrainian Man Tracks Russian Troop Movements With Stolen Airpods
data = data.append(getTranscript("zbxymrhSve8")) #'The Masked Singer' Judge Walks Off Stage During Rudy Giuliani Unveiling
data = data.append(getTranscript("rgcNd82sS4I")) #Joe: Rep. McCarthy Showed A Courage Lasting A 'Lunchtime' Over Jan. 6
data = data.append(getTranscript("ZFmEavMtNJk")) #Putin Claims Mariupol 'Success,' Zelenskyy Says Situation In Mariupol Is 'Extremely Severe'
data = data.append(getTranscript("BYzgue16TfY")) #'Outrageous And Inexcusable': Pelosi Blasts Show Leading To Capitol Evacuation
data = data.append(getTranscript("Ni2VFJXurxI")) #Watch Morning Joe Highlights: April 20 | MSNBC
data = data.append(getTranscript("YMXEvcd5ngE")) #DeSantis Calls On Legislature To Kill Disney's Special Self-Governing Status
data = data.append(getTranscript("LTriPLkN7js")) #Steve Rattner: Midterm Outlook Worsens For Democrats

data = data.append(getTranscript("Martf5RZ-wI")) #U.S. Plans To Announce More Military Aid To Ukraine
data = data.append(getTranscript("WL6YVgRcQ0g")) #'A Horrible Humanitarian Situation' If Russia Strikes Mariupol Steel Plant
data = data.append(getTranscript("J7do7Ji9CC4")) #Talks Between Russia, Ukraine Continuing But Not Getting Far, Says Ambassador
data = data.append(getTranscript("DT7DkOzeLaM")) #Michigan State Senator Blasts GOP Colleague Over Smear
data = data.append(getTranscript("hu2jprZ50FY")) #'Something Went Haywire': Why Past Decade Has Been 'Uniquely Stupid'
data = data.append(getTranscript("AFqdBAAGNt4")) #Patchwork Of Changing Rules On Masking Creates Traveler Confusion
data = data.append(getTranscript("QVF6FZ00vqw")) #Will Russia Allow Civilians Out Of Mariupol's Steel Plant?
data = data.append(getTranscript("cs6KVwK-UMU")) #Dramatic Footage Shows Woman Fainting, Falling Underneath Moving Train

data = data.append(getTranscript("YgCL4UECCGY")) #Watch Morning Joe Highlights: April 19 | MSNBC
data = data.append(getTranscript("HBCtsp22cGM")) #McFaul: You Can't Want Diplomacy If The Other Side Doesn't Want To Talk
data = data.append(getTranscript("vM91fKV_2xQ")) #Ukraine Claims To Have Leaked Personal Information Of Russian Troops, Spies
data = data.append(getTranscript("UEcEfILRc_s")) #Ukraine's Prosecutor General Investigates Russia's Alleged War Crimes
data = data.append(getTranscript("zkBKGYcaQEM")) #How Aid Organizations In Romania Are Helping Ukrainian Refugees
data = data.append(getTranscript("ba1j4NviNbw")) #Why The IMF, World Bank Important In Supporting Ukraine
data = data.append(getTranscript("LZSLu3M7Nug")) #Biden Set To Push For More Consequences To Russia In Call With Allies
data = data.append(getTranscript("Nr7rsE2mZvo")) #Judge Strikes Down CDC Transportation Mask Mandate

#in a nutshell
data = data.append(getTranscript("EhAemz1v7dQ")) #Do we Need Nuclear Energy to Stop Climate Change?
data = data.append(getTranscript("wbR-5mHI6bo")) #Is It Too Late To Stop Climate Change? Well, it's Complicated.
data = data.append(getTranscript("ck4RGeoHFko")) #Was ist Intelligenz? Wo beginnt sie?
data = data.append(getTranscript("QImCld9YubE")) #Warum lebst du? – Leben, Energie & ATP
data = data.append(getTranscript("5iPH-br_eJQ")) #Was wäre, wenn wir eine Atombombe auf eine Stadt fallen lassen würden?
data = data.append(getTranscript("ipVxxxqwBQw")) #Wer ist verantwortlich für den Klimawandel? Wer muss ihn beheben?
data = data.append(getTranscript("9P6rdqiybaw")) #Wurmlöcher erklärt - Das Brechen des Raum-Zeit Kontinuums
data = data.append(getTranscript("-O5kNPlUV7w")) #Warum uns schöne Dinge glücklich machen - Schönheit erklärt

data = data.append(getTranscript("Da-2h2B4faU")) #Stringtheorie Erklärt - Was ist die wahre Natur der Realität?
data = data.append(getTranscript("8PmM6SUn7Es")) #Ist "Bio" wirklich besser? Gesundes Essen oder Marken-Betrug?
data = data.append(getTranscript("yS1ibDImAYU")) #Das Ende vom Weltraum – Erstellung eines Gefängnisses für die Menschheit
data = data.append(getTranscript("NxvQPzrg2Wg")) #Warum Fleisch die beste schlechteste Sache der Welt ist 🍔
data = data.append(getTranscript("RS7IzU2VJIQ")) #Plastikverschmutzung: Wie Menschen die Welt in Plastik verwandeln
data = data.append(getTranscript("YI3tsmFsrOg")) #Das tödlichste Wesen auf dem Planeten Erde - der Bakteriophage
data = data.append(getTranscript("5TbUxGZtwGI")) #Zeit: Die Geschichte & Zukunft von allem – Remastered
data = data.append(getTranscript("8HslUzw35mc")) #Homöopathie – Sanfte Alternative oder Dreister Humbug?

#ABC News
data = data.append(getTranscript("i4FYfH3oqXs")) #Protester hospitalised with COVID as Victoria posts highest ever daily COVID case rise | ABC News
data = data.append(getTranscript("EXjTEUMlHBw")) #Protesters march through Melbourne's CBD in wake of construction industry shutdown | 7.30
data = data.append(getTranscript("CkVPhFRv-TM")) #More than 200 protesters arrested at Melbourne's Shrine of Remembrance | ABC News
data = data.append(getTranscript("y1hVnLX1goI")) #CFMEU's Dave Noonan claim "very few" union members were involved in Melbourne's protests | 7.30
data = data.append(getTranscript("WBLKkfDtoIE")) #'This is not who we are': Melbourne Lord Mayor Sally Capp reflects on the protests | 7.30
data = data.append(getTranscript("iOng2MOTM7Y")) #Outrage following protesters' use of Shrine of Remembrance in Melbourne | ABC News
data = data.append(getTranscript("Pro_5njLkRw")) #Construction protests an 'insult' to building industry says Premier | ABC News
data = data.append(getTranscript("-jQiSTHwd4o")) #IN FULL: Daniel Andrews address anti-lockdown protests | ABC News

data = data.append(getTranscript("3vK6q-9vWIE")) #IN FULL: Victoria Police have made 62 arrests so far and three police officers injured | ABC News
data = data.append(getTranscript("tAJv8LrG9ag")) #Protesters storm through Melbourne's CBD | ABC News
data = data.append(getTranscript("myp-Hp7O9Qg")) #Melbourne freeway blocked as hundreds protest construction industry restrictions | ABC News
data = data.append(getTranscript("vd1XZA-UJ9A")) #Vic. construction industry told to down tools after violent protests | ABC News
data = data.append(getTranscript("EKQTqW-D2Es")) #Ukrainian troops make final stand in Mariupol as Putin's army tightens grip on the east | ABC News
data = data.append(getTranscript("pqsKhn9MGS8")) #Fresh attempt to evacuate thousands from Mariupol fails | ABC News
data = data.append(getTranscript("W_BT6oEG5FU")) #Russian forces attack multiple cities in Ukraine's east | ABC News
data = data.append(getTranscript("hoeX_lx8e0s")) #Boris Johnson apologises for breaching COVID lockdown rules | ABC News

data = data.append(getTranscript("nAlIQjuO_hA")) #Russia begins next phase of the war, says Ukraine | ABC News
data = data.append(getTranscript("GyzWdGpDavM")) #Prince Harry and Meghan meet Queen during Windsor Castle visit | ABC News
data = data.append(getTranscript("1uFKkFXrt58")) #UK planning to send asylum seekers arriving by boat to Rwanda | ABC News
data = data.append(getTranscript("pkDF8BYvmug")) #Nightclub stockpiles much-needed food and medical supplies in Kyiv | ABC News
data = data.append(getTranscript("By1WoOBw1YM")) #French President Emmanuel Macron and Marine Le Pen to face each other in run-off vote | ABC News
data = data.append(getTranscript("LWlAKKvUIZI")) #Macron and Le Pen lead French election first round, heading for runoff | ABC News
data = data.append(getTranscript("O_dYVgDhgM8")) #First Australian Bushmasters on their way to Ukraine | ABC News
data = data.append(getTranscript("LIxCwnBpEFE")) #Russia suspended from UN Human Rights Council | ABC News

data = data.append(getTranscript("8ULw_YxqGms")) #Afghan refugees call on government to grant them permanent protection | ABC News
data = data.append(getTranscript("qSxdLoFNN5c")) #Afghan army deserter who killed three Australian soldiers freed from custody | ABC News
data = data.append(getTranscript("7YnUgmLfpEk")) #America's top military general says Al Qaeda could attack US in a year | ABC News
data = data.append(getTranscript("mu8GxAPoNDs")) #Taliban 2.0 a 'marketing gimmick' for international community | The World
data = data.append(getTranscript("AMC5_JnPqC0")) #Escaping the Taliban to reach Australia | Afghanistan | ABC News
data = data.append(getTranscript("qxAbbSB912c")) #What the Taliban doesn’t want you to know | ABC News
data = data.append(getTranscript("jm4ODIQ69Fs")) #UN condemns Taliban's violent crackdown on protesters and journalists | ABC News
data = data.append(getTranscript("n9E65RuH_Pk")) #Thousands attempt to escape Afghanistan at Torkham border | ABC News

data = data.append(getTranscript("KFI4TTCMAng")) #Cricket Australia makes a stand on Taliban's ban for women's sport | ABC News
data = data.append(getTranscript("MHJsnFlVRlA")) #Afghans on the border describe why they're leaving their home country | ABC News
data = data.append(getTranscript("50FYwO7Q5M8")) #Afghans start new life after quarantine in Adelaide | ABC News
data = data.append(getTranscript("xXAtAWxKBeE")) #Taliban breaks up women's rights protests posing problem for new Afghanistan government | ABC News
data = data.append(getTranscript("zFop-UE4c5w")) #Who is Mohammad Hasan Akhund? Stan Grant's analysis of the Taliban's interim government | ABC News
data = data.append(getTranscript("aVPp4oKxDGQ")) #Former ADF interpreter left in limbo after botched visa decision from Australian govt | ABC News
data = data.append(getTranscript("flNXjMFzjsM")) #Taliban claim control of last holdouts in Afghanistan — but resistance say they'll fight | ABC News
data = data.append(getTranscript("ueXDAKUXMj0")) #Taliban approves Australian cricket match, but women's team status could bring it undone | ABC News

data = data.append(getTranscript("1RY3ymvyOZo")) #Taliban closes in on Panjshir region as Kabul women protest for equal rights | ABC News
data = data.append(getTranscript("a-pNxGZeXE4")) #Could the US ally with the Taliban if it wants to continue strikes against IS-K? | ABC News
data = data.append(getTranscript("virT4y2nNh0")) #US President Biden praises Afghan evacuation effort, defends departure from 'forever war' | ABC News
data = data.append(getTranscript("uP5W0neGNPw")) #United States completes withdrawal from Afghanistan after final plane leaves Kabul | ABC News
data = data.append(getTranscript("NalShzAgqlY")) #Mass evacuation of Afghans and foreign nationals enters its final hours | ABC News
data = data.append(getTranscript("SVeHGIZIZYQ")) #Double suicide bombing at Kabul airport kills at least 60, including 13 US troops | ABC News
data = data.append(getTranscript("vcHgO8ge6Sg")) #Who are ISIS-K and where did they come from? | ABC News
data = data.append(getTranscript("IXSZDKF_OUk")) #IN FULL: PM Scott Morrison addresses Afghanistan attacks | ABC News

#CBC News
data = data.append(getTranscript("KhiwoZ_rRwY")) #International group of scientists searches for alien technology
data = data.append(getTranscript("baF9L04iRWA")) #Feds, First Nations reach $8-billion settlement on boil-water lawsuits
data = data.append(getTranscript("etGdzlnro-I")) #Singh reacts to Indigenous drinking water settlement, looming election
data = data.append(getTranscript("-3xsaT5wTeo")) #Tam says vaccinations will determine severity of 4th wave
data = data.append(getTranscript("Tud9mIlyPr4")) #Scientists fear extreme weather events reaching irreversible climate thresholds
data = data.append(getTranscript("6UDAcqdOEmo")) #Going back to the office? Here’s what business leaders say to expect
data = data.append(getTranscript("XIqND1s-I6Q")) #How this mayor tackled vaccine hesitancy in a deeply Republican city
data = data.append(getTranscript("hhVMS0MSx5E")) #Canada must swiftly resettle Afghan interpreters, retired colonel says

data = data.append(getTranscript("6icsDCzbuJQ")) #Mask mandate reintroduced in parts of B.C. amid rising cases
data = data.append(getTranscript("MxuJL2vY5yI")) #Albertans losing trust in province's COVID-19 messaging, Edmonton doctor says
data = data.append(getTranscript("XUVCdbRdOWQ")) #N.L. premier says federal-provincial Muskrat Falls deal gives 'breathing room'
data = data.append(getTranscript("cwta_PQFL-U")) #Nishnawbe Aski Nation disappointed after meeting Ford government about Ontario wildfires

data = data.append(getTranscript("YWs54GvEd9E")) #No demand for J&J vaccines from provinces, minister says
data = data.append(getTranscript("kggeFheNg1c")) #Border workers vote to strike, jeopardizing Canada's reopening plans
data = data.append(getTranscript("5FDgEZWSNsc")) #Bradley Barton sentenced to 12½ years for death of Cindy Gladue

data = data.append(getTranscript("-hyU4dlRyHk")) #Grassy Narrows First Nation secures $68.9M in funding for mercury care
data = data.append(getTranscript("hgo_RWycPxk")) #Inuk throat singer and activist reacts to Mary Simon's installation as governor general
data = data.append(getTranscript("r2QY0akuBZA")) #Chief Justice Richard Wagner reflects on his tenure as interim governor general
data = data.append(getTranscript("1QXxL_hC6Ow")) #Mary Simon installed as Canada's 30th Governor General | CBC News Special
data = data.append(getTranscript("nU456jqFeIg")) #Travellers with mixed vaccines say they can't board some cruises
data = data.append(getTranscript("ujYLXlQShqU")) #How to stop ducklings from falling through the cracks
data = data.append(getTranscript("p-GuAPHkcMU")) #Cyclist Michael Woods surprised by wife Elly on TV after race
data = data.append(getTranscript("_EYUc1kVcZI")) #Uncertainty remains for evacuees and those on alert due to wildfires in B.C.

data.to_csv("TranscriptSegmentation.csv")

